import { defaultSchema } from "rehype-sanitize";

import type { Options as SanitizeSchema } from "rehype-sanitize";

/** 允许常见 Markdown HTML + KaTeX / highlight 产出标签与属性 */
export const markdownSanitizeSchema: SanitizeSchema = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "video",
    "source",
    "iframe",
    "section",
    "figure",
    "figcaption",
    "math",
    "semantics",
    "mrow",
    "mi",
    "mo",
    "mn",
    "ms",
    "mtext",
    "annotation",
    "mfrac",
    "msup",
    "msub",
    "msubsup",
    "munder",
    "mover",
    "munderover",
    "msqrt",
    "mroot",
    "mtable",
    "mtr",
    "mtd",
    "mstyle",
    "mspace",
    "mpadded",
    "mphantom",
    "menclose",
  ],
  attributes: {
    ...defaultSchema.attributes,
    h1: [...(defaultSchema.attributes?.h1 ?? []), ["id"]],
    h2: [...(defaultSchema.attributes?.h2 ?? []), ["id"]],
    h3: [...(defaultSchema.attributes?.h3 ?? []), ["id"]],
    h4: [...(defaultSchema.attributes?.h4 ?? []), ["id"]],
    h5: [...(defaultSchema.attributes?.h5 ?? []), ["id"]],
    h6: [...(defaultSchema.attributes?.h6 ?? []), ["id"]],
    code: [...(defaultSchema.attributes?.code ?? []), ["className"], ["class"]],
    span: [
      ...(defaultSchema.attributes?.span ?? []),
      ["className"],
      ["class"],
      ["style"],
      ["ariaHidden"],
      ["ariaLabel"],
    ],
    div: [...(defaultSchema.attributes?.div ?? []), ["className"], ["class"], ["style"]],
    pre: [...(defaultSchema.attributes?.pre ?? []), ["className"], ["class"]],
    a: [...(defaultSchema.attributes?.a ?? []), ["className"], ["class"], ["target"], ["rel"]],
    img: [...(defaultSchema.attributes?.img ?? []), ["className"], ["class"], ["loading"]],
    table: [...(defaultSchema.attributes?.table ?? []), ["className"], ["class"]],
    th: [...(defaultSchema.attributes?.th ?? []), ["className"], ["class"], ["align"], ["style"]],
    td: [...(defaultSchema.attributes?.td ?? []), ["className"], ["class"], ["align"], ["style"]],
    iframe: [
      ["src"],
      ["width"],
      ["height"],
      ["allow"],
      ["allowFullScreen"],
      ["frameBorder"],
      ["title"],
      ["className"],
      ["class"],
    ],
    video: [["src"], ["controls"], ["width"], ["height"], ["className"], ["class"]],
    source: [["src"], ["type"]],
    math: [["xmlns"], ["display"]],
    annotation: [["encoding"]],
    mspace: [["width"], ["height"], ["depth"]],
    mstyle: [["mathcolor"], ["mathbackground"], ["scriptlevel"]],
  },
};
